services:
  supir-extended:
    image: adriabama06/supir-extended
    build:
      dockerfile: Dockerfile
      context: .
    network_mode: bridge
    container_name: supir-extended
    healthcheck:
      test: curl --fail http://localhost:6688 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - 6688:6688
    volumes:
      - models:/app/models
      - outputs:/app/outputs
      - ./entrypoint.sh:/app/entrypoint.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # To use specifics GPUs --> device_ids: ['0']
              capabilities: [gpu]

volumes:
  models:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./models
  outputs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./outputs
